spring.application.name=MoneyT
moneyT.app.jwtSecret=
moneyT.app.jwtExpirationMs=86400000

spring.datasource.url=
spring.datasource.driverClassName=
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

